[[plugins]]
  package = "@netlify/plugin-local-install-core"

[build.environment]
  NPM_FLAGS="--version"
  NODE_VERSION="16"

[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"