[[plugins]]
  package = "@netlify/plugin-local-install-core"

[[plugins]]
  package = "./plugins/netlify-plugin-csp-generator-ext"

  [plugins.inputs]
    buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    scriptSrc = "'self' 'unsafe-inline' https://www.googletagmanager.com https://ssl.google-analytics.com https://www.google-analytics.com"
    connectSrc = "'self' https://fonts.googleapis.com https://fonts.gstatic.com https://www.googletagmanager.com https://ssl.google-analytics.com https://*.google-analytics.com"
    styleSrc = "'self' 'unsafe-inline' https://fonts.googleapis.com"
    baseUri = "'self'"
    formAction = "'self'"
    manifestSrc = "'self'"
    imgSrc = "'self' data: https://www.googletagmanager.com https://*.google-analytics.com"
    frameSrc = "'self' https://utteranc.es"
    fontSrc = "https://fonts.gstatic.com"
    workerSrc = "'self'"

[build.environment]
  NPM_FLAGS="--version"
  NODE_VERSION="16"

[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"