[[plugins]]
  package = "netlify-plugin-csp-generator"

  [plugins.inputs]
    buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    scriptSrc = "'self' 'unsafe-inline' 'sha256-piLB37L5b4J10UONJEev/t4UApgd9sCS5bozyDOd0EE=' 'sha256-gqzXenpKzr3O5bJrzpok53/0HRakwHq6ZXD7bn3aPeI=' 'sha256-fNermfjwi1X28IW/JtOOhREaXCHb+jeaZKBaOalg6Hc=' https://www.googletagmanager.com https://ssl.google-analytics.com https://www.google-analytics.com"
    connectSrc = "'self' https://fonts.googleapis.com https://fonts.gstatic.com https://www.googletagmanager.com https://ssl.google-analytics.com https://www.google-analytics.com"
    styleSrc = "'self' 'unsafe-inline' https://fonts.googleapis.com"
    baseUri = "'self'"
    formAction = "'self'"
    manifestSrc = "'self'"
    imgSrc = "'self' data: https://www.googletagmanager.com https://www.google-analytics.com"
    frameSrc = "https://utteranc.es"
    fontSrc = "https://fonts.gstatic.com"
    workerSrc = "'self'"